name       : rxvt-unicode
version    : '9.31'
release    : 16
source     :
    - http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.31.tar.bz2 : aaa13fcbc149fe0f3f391f933279580f74a96fd312d6ed06b8ff03c2d46672e8
license    : GPL-3.0-or-later
summary    : Unicode compliant fork of rxvt, commonly refered to as urxvt
component  : utils
description: |
    Unicode compliant fork of rxvt, commonly refered to as urxvt
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libptytty)
    - pkgconfig(xext)
    - pkgconfig(xft)
    - pkgconfig(xt)
    - pkgconfig(xrender)
patterns   :
    - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/0001-wide-glyphs-and-improved-font-rendering.patch
    %configure --enable-256-color \
               --enable-combining \
               --enable-xft \
               --enable-font-styles \
               --enable-pixbuf \
               --enable-startup-notification \
               --enable-transparency \
               --enable-fading \
               --enable-rxvt-scroll \
               --enable-mousewheel \
               --enable-slipwheeling \
               --enable-smart-resize \
               --enable-text-blink \
               --enable-unicode3 \
               --enable-pointer-blank \
               --enable-utmp \
               --enable-wide-glyphs \
               --enable-perl \
               --enable-wtmp \
               --enable-lastlog
build      : |
    %make
install    : |
    %make_install
    install -d $installdir/usr/share/terminfo/
    tic -x doc/etc/rxvt-unicode.terminfo -o $installdir/usr/share/terminfo/
    install -Dm00644 $pkgfiles/rxvt-unicode.desktop $installdir/usr/share/applications/rxvt-unicode.desktop
