name       : rxvt-unicode
version    : '9.30'
release    : 15
source     :
    - http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.30.tar.bz2 : fe1c93d12f385876457a989fc3ae05c0915d2692efc59289d0f70fabe5b44d2d
license    : GPL-3.0-or-later
summary    : Unicode compliant fork of rxvt, commonly refered to as urxvt
component  : utils
description: |
    Unicode compliant fork of rxvt, commonly refered to as urxvt
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libptytty)
    - pkgconfig(xft)
    - pkgconfig(xt)
    - pkgconfig(xrender)
patterns   :
    - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/0001-wide-glyphs-and-improved-font-rendering.patch
    %configure --enable-256-color \
               --enable-combining \
               --enable-xft \
               --enable-font-styles \
               --enable-pixbuf \
               --enable-startup-notification \
               --enable-transparency \
               --enable-fading \
               --enable-rxvt-scroll \
               --enable-mousewheel \
               --enable-slipwheeling \
               --enable-smart-resize \
               --enable-text-blink \
               --enable-unicode3 \
               --enable-pointer-blank \
               --enable-utmp \
               --enable-wide-glyphs \
               --enable-perl \
               --enable-wtmp \
               --enable-lastlog
build      : |
    %make
install    : |
    %make_install
    install -d $installdir/usr/share/terminfo/
    tic -x doc/etc/rxvt-unicode.terminfo -o $installdir/usr/share/terminfo/
    install -Dm00644 $pkgfiles/rxvt-unicode.desktop $installdir/usr/share/applications/rxvt-unicode.desktop
