name       : rxvt-unicode
version    : 9.22
release    : 6
source     :
    - http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2 : e94628e9bcfa0adb1115d83649f898d6edb4baced44f5d5b769c2eeb8b95addd
license    : GPL-2.0
summary    : Unicode compliant fork of rxvt, commonly refered to as urxvt
component  : utils
description: |
    Unicode compliant fork of rxvt, commonly refered to as urxvt
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xrender)
patterns   :
    - /usr/share/man
setup      : "%configure --enable-256-color \\\n           --enable-combining \\\n\
    \           --enable-xft \\\n           --enable-font-styles \\\n           --enable-pixbuf\
    \ \\\n           --enable-startup-notification \\\n           --enable-transparency\
    \ \\\n           --enable-fading \\\n           --enable-rxvt-scroll \\\n    \
    \       --enable-mousewheel \\\n           --enable-slipwheeling \\\n        \
    \   --enable-smart-resize \\\n           --enable-text-blink \\\n           --enable-unicode3\
    \ \\\n           --enable-pointer-blank \\\n           --enable-utmp \\\n    \
    \       --enable-wtmp \\\n           --enable-lastlog               \n"
build      : |
    %make
install    : |
    %make_install
